### ISSUE TITLE
Support a input()-like command in the pyland environment

### ISSUE THREAD

**Issue by asb** [pyland/pyland#100]
It would be useful to have challenges that let the player ask for user input. It should be possible to use input() to get strings through the pyland SDL window.

**Comment by sams25** [comment]
This has been done with Alex's "open external script" method. This has been implemented in Alex's level where snakes in the level accept python scripts and my level where they accept a string from the terminal. Plus, it is now possible to get strings from both the terminal and the scripter, so I think this can be closed.
