### ISSUE TITLE
Difficulty in sharing script code between characters

### ISSUE THREAD

**Issue by davidhoness** [pyland/pyland#111]
Running on Ubuntu 14.04

I wrote some route finding code for Milo to automatically have him navigate between collecting and despositing the fruit. I then wanted to use that code for both Milo and Ben.

Instead of copying the code into both scripts I would much prefer to import it from a shared file.

My shared file contained the following code (myfile.py):
```python
def croc_seen(dist):
	is_seen = False
	seen_objects = look(dist)
	for obj in seen_objects:
		if "crocodile" in obj[0]:
			is_seen = True
	return is_seen

def try_move(delta, direction):
	while delta != 0:
		if walkable(direction):
			move(direction)
			delta -= (-1 if delta < 0 else 1)
		else:
			break
	return delta

def path_find(x_src, y_src, x_dest, y_dest):
	x_delta = x_dest - x_src
	y_delta = y_dest - y_src

	x_dir = east if x_delta >= 0 else west
	y_dir = north if y_delta >= 0 else south

	while y_delta != 0 or x_delta != 0:
		x_delta = try_move(x_delta, x_dir)
		y_delta = try_move(y_delta, y_dir)
```
Here is what I tried;
- Saving the file into `pyland/src/python_embed/scripts` and using `from myfile import *`
  - Result: `ImportError: No module named 'myfile'`
- Using `import os` and `print(os.getcwd())` to find the working folder, this was `pyland/src`, I then moved myfile.py to there and tried again.
  - Result: `ImportError: No module named 'myfile'`
- I then went for:

    ```python
    import os, sys
    sys.path.append(os.getcwd())
    from myfile import *
    ```
  - Result:

    ```
    Traceback (most recent call last):
      File "/usr/lib/python3.4/code.py", line 90, in runcode
        exec(code, self.locals)
      File "<string>", line 8, in <module>
      File "/home/dave/Documents/dev/git/pyland/src/myfile.py", line 22, in path_find
        x_dir = east if x_delta >= 0 else west
    NameError: name 'west' is not defined
    ```
So it appears that it has actually found the module however it doesn't have access to the existing in game definitions such as the direction variables. Is there some kind of clever execution context stuff going on?

Here is Milo's script:
```python
import os, sys
sys.path.append(os.getcwd())
from myfile import *

while True:
	path_find(5, 46, 3, 46)
	path_find(3, 46, 4, 42) #from Villager to Bridge

	while croc_seen(4):
		pass

	path_find(4, 42, 4, 37)
	path_find(4, 37, 15, 30)

	path_find(15, 30, 4, 40)

	while croc_seen(4):
		pass

	path_find(4,40, 4, 42)
	path_find(4, 42, 3, 46)
	path_find(3, 46, 5, 46)
```

**Comment by sams25** [comment]
We now have a set of 9 scripts that can be accessed by any character anywhere
