### ISSUE TITLE
Game Speedup

### ISSUE THREAD

**Issue by Moosichu** [pyland/pyland#185]
Make it so that when shift is held down while running scripts the game speed is increased by a fixed factor instead of running as fast as possible. (As on my laptop must scripts run in less than a frame!)

**Comment by Veedrac** [comment]
IIRC this was already implemented. Looking at https://github.com/pyland/pyland/blob/master/src/main.cpp#L222 it seems there's a factor of 511 that you can fiddle with. Lowering that should give the desired effects.

Take this comment with a grain of salt.
