### ISSUE TITLE
Player's name is not updated

### ISSUE THREAD

**Issue by alexandaday** [pyland/pyland#283]
When the player gets killed by a crocodiles, it prints that 'player_one' got killed when it should display the name of the user chose.

It seems set_name in player.py sets the player's name in character.py, so I'm not sure why it doesn't work.

**Comment by Moosichu** [comment]
Fixed this, the reason for this is because the crocodile called character.get_name() instead of character.get_character_name(), the former returns that name of the instance and the latter returns whatever you decided the character should be called in game.
